### ISSUE TITLE
Merge with wurst 2.13

### ISSUE THREAD

**Issue by ThisTestUser** [null-dev/EvenWurse#3]
I was just wondering, could this be possible? Also, is this going to still be developed?

**Comment by null-dev** [comment]
**Merge with the original Wurst repository?** Almost impossible. The coding style is completely different and it has a completely different build cycle and stuff. Alexander will 90% reject it.

**Is this still developed?** Yes actually. I only check the Wurst repository every once in a while and didn't realize it had updated. Thanks for reminding me. As for new features, maybe I'll add some but I need some recommendations on what to add...

**Comment by null-dev** [comment]
I'll see if I can update it to Wurst 2.13 by the end of the day (in my timezone).

**Comment by ThisTestUser** [comment]
I'm saying if you could merge the 2.13 to yours, not this with the original.
And what program do you use to compile your code?

**Comment by null-dev** [comment]
This projects currently uses Intellij IDEA (instead of Eclipse in the original project).

**Comment by null-dev** [comment]
I've merged in the code but I don't have enough time to do a release this week since I have exams. I'll try to get a release done ASAP.

**Comment by null-dev** [comment]
Release merged but Wurst 2.14 came out now :/. I'll open a new issue for it.
